# Generated by Django 4.1.7 on 2024-04-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ingredients', models.TextField(max_length=250)),
                ('shelf_life', models.IntegerField()),
                ('type', models.CharField(max_length=25)),
                ('amount_sold', models.IntegerField()),
                ('wasted', models.IntegerField()),
                ('vegan', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
                ('image', models.ImageField(default='https://miro.medium.com/v2/resize:fit:720/format:webp/1*EN0fyh1x46dxsc-w20lRfw.jpeg', upload_to='images')),
            ],
        ),
    ]
