# Generated by Django 4.1.7 on 2024-04-07 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='amount_sold',
        ),
        migrations.RemoveField(
            model_name='food',
            name='wasted',
        ),
    ]
