# Generated by Django 4.1.7 on 2024-04-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_remove_food_amount_sold_remove_food_wasted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='image',
        ),
    ]
