# Generated by Django 4.1.7 on 2024-04-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='ingredients',
            field=models.TextField(max_length=500),
        ),
    ]
