# Generated by Django 4.1.7 on 2024-04-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_food_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bakery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ingredients', models.TextField(max_length=1500)),
                ('date_on_box', models.IntegerField()),
                ('vegan', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
