# Generated by Django 4.1.7 on 2024-04-14 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_bakery_delete_food'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bakery',
            new_name='Bakery_Items',
        ),
    ]
