# Generated by Django 4.1.7 on 2024-04-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_rename_bakery_bakery_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bakery_Items',
            new_name='Bakery_Item',
        ),
    ]
