# Generated by Django 4.1.7 on 2024-04-14 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_rename_bakery_items_bakery_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bakery_item',
            old_name='date_on_box',
            new_name='days_in_box',
        ),
    ]
