# Generated by Django 4.1.7 on 2024-04-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_rename_date_on_box_bakery_item_days_in_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery_item',
            name='days_in_case',
            field=models.IntegerField(default=True),
        ),
    ]
