# Generated by Django 4.1.7 on 2024-04-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_bakery_item_days_in_case'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bakery_item',
            old_name='days_in_case',
            new_name='days_in_pastry_case',
        ),
    ]
