# Generated by Django 4.1.7 on 2024-04-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_rename_days_in_case_bakery_item_days_in_pastry_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakery_item',
            name='days_in_box',
        ),
        migrations.RemoveField(
            model_name='bakery_item',
            name='days_in_pastry_case',
        ),
        migrations.AddField(
            model_name='bakery_item',
            name='time_in_box',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='bakery_item',
            name='time_in_pastry_case',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
