# Generated by Django 4.1.7 on 2024-04-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_remove_bakery_item_days_in_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery_item',
            name='sku',
            field=models.IntegerField(default=0),
        ),
    ]
