# Generated by Django 4.1.7 on 2024-04-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_bakery_item_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chilled_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sku', models.IntegerField(default=0)),
                ('ingredients', models.TextField(max_length=1500)),
                ('vegan', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
            ],
        ),
    ]
