# Generated by Django 4.1.7 on 2024-04-15 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_chilled_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chilled_Item',
            new_name='Sandwiches_and_Prepared_Food',
        ),
    ]
