# Generated by Django 4.1.7 on 2024-04-22 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0020_porridge_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bakery_Item',
        ),
        migrations.DeleteModel(
            name='Egg_Bite',
        ),
        migrations.DeleteModel(
            name='Pastry_Item',
        ),
        migrations.DeleteModel(
            name='Porridge_Item',
        ),
        migrations.DeleteModel(
            name='Sandwiches_and_Prepared_Food',
        ),
    ]
